id = "nomad"
name = "Nomad"
version = "0.0.2"
schema_version = 1
authors = ["loczek"]
description = "Nomad Language Server"
repository = "https://github.com/loczek/zed-nomad-extension"

[language_servers.nomad-ls]
name = "Nomad Language Server"
languages = [
    "Nomad ACL",
    "Nomad Agent",
    "Nomad Job",
    "Nomad Namespace",
    "Nomad Node Pool",
    "Nomad Resource Quota",
    "Nomad Variable",
    "Nomad CSI Volume",
    "Nomad Dynamic Host Volume"
]

[language_servers.nomad-ls.language_ids]
"Nomad ACL" = "nomad-acl"
"Nomad Agent" = "nomad-agent"
"Nomad Job" = "nomad-job"
"Nomad Namespace" = "nomad-namespace"
"Nomad Node Pool" = "nomad-node-pool"
"Nomad Resource Quota" = "nomad-resource-quota"
"Nomad Variable" = "nomad-variable"
"Nomad CSI Volume" = "nomad-volume-csi"
"Nomad Dynamic Host Volume" = "nomad-volume-dynamic-host"

[grammars.hcl]
repository = "https://github.com/MichaHoffmann/tree-sitter-hcl"
rev = "64ad62785d442eb4d45df3a1764962dafd5bc98b"
